esphome:
  name: ld2412-esp32-c3
  friendly_name: LD2412-ESP32-C3

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "uUw2+1tFAPp43Gcyiw4rUaeaSWh8Ln77iiKlZxdkTyI="

ota:
  - platform: esphome
    password: "ab6207ac17496352be3772639c4e33be"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ld2412-Esp32-C3 Fallback Hotspot"
    password: "xBqlRr752iI2"

captive_portal:
    